language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"

env:
  - DJANGO=Django==1.4.20
  - DJANGO=Django==1.5.11
  - DJANGO=Django==1.6.8
  - DJANGO=Django==1.7.7
  - DJANGO=Django==1.8

matrix:
  allow_failures:
    # Allow failures for Python 3.3
    - python: "3.3"
  exclude:
    # Django 1.4 and 1.5 do not fully support Python 3.3
    - env: DJANGO=Django==1.4.20
      python: "3.3"
    - env: DJANGO=Django==1.5.7
      python: "3.3"
    # Django > 1.7 doesn't support Python 2.6 anymore
    - env: DJANGO=Django==1.7.7
      python: "2.6"
    - env: DJANGO=Django==1.8
      python: "2.6"

# command to install dependencies
install:
  - pip install $DJANGO
  - pip install -r requirements.txt

# command to run tests
script: python setup.py test
